#!/bin/bash
#Script to backup my DietPi logs and the DietPi internal backup off of the USB stick
project=LEO-DHCP
projroot=/mnt/nfs/export/
#$project is the name of the project/stack being backed up. It's used for the index path in bup init.
#$projroot is the root of the project folder - a seperate index will be created for each subdirectory in this path.


readarray -t names < <(find $projroot -mindepth 1 -maxdepth 1 -type d | sed "s,${projroot},,g") #This runs find on $projroot with a min/max depth of 1, for directories. It then sed's it so remove $projroot so we have just the names of the directories we want to backup. This is all then fed into readarray to make the array "$names".
total=${#names[@]} #This counts how many elements the array $names has, and sets $total to that value.


printf '%s\n\n' "Running bup init..."

count=0
for i in "${names[@]}"
do
    count=$[ $count + 1 ]
    printf -- '-%.0s\n' {1..$(tput cols)}
    printf '%s\n' "Backup $count of $total: $i"
    echo "bup -d /bup/index/$project/$i init -r BupServer:/bup/$project/$i"
done





